### ISSUE TITLE
useRequestAnimationFrame hook gives "Object(...) is not a function error" on SSR

### ISSUE THREAD

**Issue by ThaoD5** [beautifulinteractions/beautiful-react-hooks#67] opened 2020-02-21 11:24 UTC
**Tried to use useRequestAnimationFrame on a project and when trying to use it, I end up with Object(...) is not a function error**

**To Reproduce**
1. Import `import { useRequestAnimationFrame } from 'beautiful-react-hooks';`
2. Add the hook in the component 
```
import { useRequestAnimationFrame } from 'beautiful-react-hooks';

const MyComponent = ({ someProp, ...props }) => {
    const options = { finishAt: -1 };

    useRequestAnimationFrame((progress, next) => {
       console.log('test');
    }, options);

    return (
        <div />
    );
};
```
3. Go to webpage

**Expected behavior**
Obviously, have an RAF loop

**Desktop (please complete the following information):**
 - OS: High sierra 10.13.6
 - Browser: Chrome 79.0.3945.130 

**Additional context**
Project is using Next.js

**Comment by antonioru** [comment] 2020-02-21 11:42
Hi @ThaoD5 
thank you for testing it out and for finding the possible bug, I really appreciate it! 👍
I've tried to reproduce the bug but it seems to work fine on my end:

https://beautifulinteractions.github.io/beautiful-react-hooks/#/useRequestAnimationFrame 

Since you're using Next.js could it be that you're trying to perform the hook whilst server side rendering?
If so, `useRequestAnimationFrame` will try to access to the window.requestAnimationFrame API that probably only exists on the window object (so not on the SSR phase). 

I'm not a big fan of Next.js so I'm not sure if you can actually use this kind of window API whilst server side rendering, but for sure the hook shall at least report that the API is not available. 

Please feel free to open a MR about that, I would love that! 
Recently an other good developer faced a similar problem on `useMediaQuery` and added a SSR warning, check it out

**Comment by ThaoD5** [comment] 2020-02-21 11:46
Hello @antonioru , thanks for the fast answer.

I wondered too if that could be because of SSR and tried to wrap the hook inside a condition like this : 
```
if (process.browser) {
    const options = { finishAt: -1 };

    useRequestAnimationFrame(() => {
      console.log('resize');
    }, options);
  }
``` 

Unfortunately this ends up in the same error than previously

**Comment by antonioru** [comment] 2020-02-21 11:49
@ThaoD5 
You shan't wrap hooks into conditionals as [reported by the React documentation](https://reactjs.org/docs/hooks-rules.html), I would suggest to simply to use that hook for server side rendered components

**Comment by ThaoD5** [comment] 2020-02-21 11:52
Sure, this was just a try to have some more infos or a hint of a solution. 
Not sure to understand your suggestion though, did you mean "to simply not use that hook ..." ?

**Comment by antonioru** [comment] 2020-02-21 12:04
Sorry, what I meant with my suggestion is: 
when using server side rendering (so when using Next.js) do not use `useRequestAnimationFrame` since it doesn't have any support to SSR yet. 
In future it will probably give a warning...

**Comment by antonioru** [comment] 2020-02-21 13:31
@ThaoD5 I've recently updated the codebase now `useRequestAnimationFrame` should warn when rendering on server side, please let me know if you see the notification so I can possibly close the issue

**Closed** 2020-03-01 14:07 UTC
Labels: bug
